@rootURL=http://localhost:7181

GET {{rootURL}}/api/StartJobFunction

### 

POST {{rootURL}}/api/StartJobFunction
Content-Type: application/json; charset=utf-8

{
  "jobId": "594e5b37-3bfe-4884-96ef-b9db4db64b5d"
}

